Parameters:
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Provide a Key Pair Name"

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-018e1dad574748a56 
      GroupDescription: "Security Group for Instance Created Using Cloudformation."
      SecurityGroupIngress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "Vishwas-EC2-CF-Sg"

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      ImageId: ami-0574da719dca65348
      InstanceType: t2.micro
      SecurityGroupIds: 
        - !Ref EC2SecurityGroup

      Tags:
        - Key: "Name"
          Value: "VishwasEC2-CF-VPC"
